version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain hello-server-domain --domain-owner 518082434600 --region eu-west-1 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
      - printf '[{"name":"hello-server","imageUri":"%s"}]' 156041444956.dkr.ecr.eu-west-1.amazonaws.com/hello-server:latest > imagedefinitions.json     
artifacts:
  files:
    - imagedefinitions.json
    - target/app.jar
    - buildspec_docker.yml
  discard-paths: no
