version: 0.2

phases:
  install:
    runtime-versions:
      # java: corretto8
      java: openjdk8
  pre_build:
    commands:
      - echo Initializing environment
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
      - mvn -Dmaven.test.skip package
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
      - printf '[{"name":"server","imageUri":"%s"}]' 156041444956.dkr.ecr.eu-west-1.amazonaws.com/server:latest > imagedefinitions.json     
artifacts:
  files:
    - imagedefinitions.json
    - target/app.jar
    - buildspec_docker.yml
  discard-paths: no
